version: "2"

services:

  app:
    build: .
    network_mode: "host"
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app
    environment:
      - LLM=xinference
      - EMBEDDING=xinference
      - XINFERENCE_SERVER_ENDPOINT=http://127.0.0.1:9997
      - XINFERENCE_EMBEDDING_MODEL_UID=031ea20e-7889-11ee-b84e-047c1643e4f5
      - XINFERENCE_LLM_MODEL_UID=adc14cc0-7889-11ee-b84e-047c1643e4f5
